### ISSUE TITLE
Gem::ConflictError: Unable to activate activesupport-5.2.3, because tzinfo-2.0.0 conflicts with tzinfo (~> 1.1)

### ISSUE THREAD

**Issue by mokaymakci** [y-ken/fluent-plugin-twitter#46]
Hi folks,

I am using td-agent 3.5.1 and fluent-plugin-sql 1.1.1. When I start the service then a gem conflict error occurs:

```
-- A start job for unit td-agent.service has begun execution.
-- 
-- The job identifier is 4773.
  fluentd[8590]: /opt/td-agent/embedded/lib/ruby/site_ruby/2.4.0/rubygems/specification.rb:2290:in `raise_if_conflicts': Unable to activate activesupport-5.2.3, because tzinfo-2.0.0 conflicts with tzinfo (~> 1.1) (Gem::ConflictError)
  fluentd[8590]:         from /opt/td-agent/embedded/lib/ruby/site_ruby/2.4.0/rubygems/specification.rb:1410:in `activate'
  fluentd[8590]:         from /opt/td-agent/embedded/lib/ruby/site_ruby/2.4.0/rubygems/specification.rb:1444:in `block in activate_dependencies'
  fluentd[8590]:         from /opt/td-agent/embedded/lib/ruby/site_ruby/2.4.0/rubygems/specification.rb:1430:in `each'
  fluentd[8590]:         from /opt/td-agent/embedded/lib/ruby/site_ruby/2.4.0/rubygems/specification.rb:1430:in `activate_dependencies'
  fluentd[8590]:         from /opt/td-agent/embedded/lib/ruby/site_ruby/2.4.0/rubygems/specification.rb:1412:in `activate'
  fluentd[8590]:         from /opt/td-agent/embedded/lib/ruby/site_ruby/2.4.0/rubygems.rb:220:in `rescue in try_activate'
  fluentd[8590]:         from /opt/td-agent/embedded/lib/ruby/site_ruby/2.4.0/rubygems.rb:213:in `try_activate'
  fluentd[8590]:         from /opt/td-agent/embedded/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:126:in `rescue in require'
  fluentd[8590]:         from /opt/td-agent/embedded/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:39:in `require'
  fluentd[8590]:         from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluent-plugin-sql-1.1.1/lib/fluent/plugin/in_sql.rb:23:in `<module:Plugin>'
  fluentd[8590]:         from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluent-plugin-sql-1.1.1/lib/fluent/plugin/in_sql.rb:21:in `<top (required)>'
  fluentd[8590]:         from /opt/td-agent/embedded/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  fluentd[8590]:         from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.7.4/lib/fluent/registry.rb:102:in `block in search'
  fluentd[8590]:         from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.7.4/lib/fluent/registry.rb:99:in `each'
  fluentd[8590]:         from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.7.4/lib/fluent/registry.rb:99:in `search'
  fluentd[8590]:         from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.7.4/lib/fluent/registry.rb:44:in `lookup'
  fluentd[8590]:         from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.7.4/lib/fluent/plugin.rb:146:in `new_impl'
  fluentd[8590]:         from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.7.4/lib/fluent/plugin.rb:100:in `new_input'
  fluentd[8590]:         from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.7.4/lib/fluent/root_agent.rb:315:in `add_source'
  fluentd[8590]:         from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.7.4/lib/fluent/root_agent.rb:160:in `block in configure'
  fluentd[8590]:         from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.7.4/lib/fluent/root_agent.rb:156:in `each'
  fluentd[8590]:         from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.7.4/lib/fluent/root_agent.rb:156:in `configure'
  fluentd[8590]:         from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.7.4/lib/fluent/engine.rb:131:in `configure'
  fluentd[8590]:         from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.7.4/lib/fluent/engine.rb:96:in `run_configure'
  fluentd[8590]:         from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.7.4/lib/fluent/supervisor.rb:812:in `run_configure'
  fluentd[8590]:         from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.7.4/lib/fluent/supervisor.rb:589:in `dry_run'
  fluentd[8590]:         from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.7.4/lib/fluent/supervisor.rb:607:in `supervise'
  fluentd[8590]:         from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.7.4/lib/fluent/supervisor.rb:512:in `run_supervisor'
  fluentd[8590]:         from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.7.4/lib/fluent/command/fluentd.rb:324:in `<top (required)>'
  fluentd[8590]:         from /opt/td-agent/embedded/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  fluentd[8590]:         from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.7.4/bin/fluentd:8:in `<top (required)>'
  fluentd[8590]:         from /opt/td-agent/embedded/bin/fluentd:23:in `load'
  fluentd[8590]:         from /opt/td-agent/embedded/bin/fluentd:23:in `<main>'
  systemd[1]: td-agent.service: Control process exited, code=exited, status=1/FAILURE

```

and my td-agent.conf is below:

```

# system settings
<system>
  log_level warn
  workers 8
</system>

## built-in TCP input
## @see http://docs.fluentd.org/articles/in_forward
<source>
  @type forward
  @id input_forward
  tag app.log
</source>

# sp logs
<worker 0>
 <source>
  @type sql
  @log_level warn

  host localhost
  database postgres_demo
  adapter postgresql
  username ***
  password ***
 
  tag_prefix local.postgres  

  select_interval 5s  
  select_limit 500     

  state_file /var/run/fluentd/sql_state

  <table>
   table public.sample
   tag demo.optional
   update_column id
  </table>

 </source>
</worker>

## live debugging agent
<source>
  @type debug_agent
  @id input_debug_agent
  bind 127.0.0.1
  port 24230
</source>

# parse JSON log field
<filter app.log>
 @type parser
 key_name log
 reserve_time true
 reserve_data true
 remove_key_name_field true
 <parse>
   @type json
 </parse>
</filter>

## match tag=debug.** and dump to console
<match debug.**>
  @type stdout
  @id output_stdout
</match>


## elastic search output
<match app.log local.postgres**>
  @type elasticsearch
  host localhost
  port 9200
  index fluentd
  logstash_format true
  reload_connections false
  reconnect_on_error true
  reload_on_failure true
  logstash_prefix fluentd
  <buffer>
    @type file
    path /var/log/td-agent/buffer/td
  </buffer>
</match>
```

tzinfo 2.0 conflictis with  tzinfo 1.1, how could I fix this? Is there an update for this problem?

Thank you.

**Comment by mokaymakci** [comment]
Sorry, wrong repository, I am closing the issue.
